/**
 * useCmsMediaResponsive — Phase D.c (2026-05-10) responsive image hook.
 *
 * Returns both the canonical CMS media URL AND a `srcset` string built
 * from the `media.variants` map (mobile/tablet/desktop) so a `<Image>`
 * or plain `<img>` can serve the right pixel-density per device.
 *
 * Empty CMS → fallbackSrc only (no srcset). Populated CMS → original +
 * variants. The hook reuses `useCmsMedia`'s 60s cache so no extra fetches.
 *
 * Usage:
 *   const { src, srcSet, sizes } = useCmsMediaResponsive(
 *     'homepage.hero.image',
 *     '/images/hero-fallback.png',
 *     { sizes: '(max-width: 768px) 100vw, 50vw' },
 *   );
 *   <img src={src} srcSet={srcSet} sizes={sizes} alt="..." />
 *
 * Backend contract: GET /cms-media/by-key returns
 *   { url, width, height, variants: { mobile: { url, w }, tablet: ..., desktop: ... } }
 * Variants are generated by `Backend/backend/src/lib/image-resize.js` on
 * upload. When the original is smaller than a given breakpoint, that
 * breakpoint is omitted from variants — we just don't include it in srcset.
 */

'use client';

import { useEffect, useState } from 'react';
import axiosInstance from '../axios/axiosInstance';

const _cache = new Map(); // ${country}:${key} → { url, srcSet, sizes, width, height }
const TTL_MS = 60_000;

function cacheGet(key) {
  const e = _cache.get(key);
  if (!e) return null;
  if (Date.now() - e.t > TTL_MS) { _cache.delete(key); return null; }
  return e.v;
}
function cacheSet(key, v) { _cache.set(key, { v, t: Date.now() }); }

function readCookie(name) {
  if (typeof document === 'undefined') return null;
  const m = document.cookie.match(new RegExp(`(?:^|; )${name}=([^;]*)`));
  return m ? decodeURIComponent(m[1]) : null;
}
function getActiveCountry() {
  return (readCookie('qh_country') || 'IN').toUpperCase();
}

// Build the `srcset` attribute string from the variants map.
// Skips entries with a missing url. The widest variant goes last by convention.
function buildSrcSet(originalUrl, originalWidth, variants) {
  if (!variants || typeof variants !== 'object') return '';
  const entries = [];
  // Order matters for browser hint clarity: smallest → largest.
  const order = ['mobile', 'tablet', 'desktop'];
  for (const k of order) {
    const v = variants[k];
    if (v?.url && v?.w) entries.push({ url: v.url, w: Number(v.w) });
  }
  if (originalUrl && originalWidth) {
    entries.push({ url: originalUrl, w: Number(originalWidth) });
  }
  return entries.map((e) => `${e.url} ${e.w}w`).join(', ');
}

const DEFAULT_SIZES = '(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw';

export function useCmsMediaResponsive(key, fallbackSrc, opts = {}) {
  const country = getActiveCountry();
  const cKey = `${country}:${key}`;

  // Initial state from cache (or fallback). Prevents the empty-frame flash.
  const initial = cacheGet(cKey) || { url: fallbackSrc, srcSet: '', sizes: opts.sizes || DEFAULT_SIZES, width: 0, height: 0 };
  const [state, setState] = useState(initial);

  useEffect(() => {
    const cached = cacheGet(cKey);
    if (cached) { setState(cached); return; }

    let cancelled = false;
    axiosInstance.get('/cms-media/by-key', { params: { key, country } })
      .then((r) => {
        if (cancelled) return;
        const m = r?.data?.data || null;
        if (!m?.url) {
          // No CMS asset — use the fallback (no srcset to populate).
          const v = { url: fallbackSrc, srcSet: '', sizes: opts.sizes || DEFAULT_SIZES, width: 0, height: 0 };
          cacheSet(cKey, v);
          setState(v);
          return;
        }
        const v = {
          url:    m.url,
          srcSet: buildSrcSet(m.url, m.width, m.variants),
          sizes:  opts.sizes || DEFAULT_SIZES,
          width:  m.width  || 0,
          height: m.height || 0,
        };
        cacheSet(cKey, v);
        setState(v);
      })
      .catch(() => {
        if (cancelled) return;
        const v = { url: fallbackSrc, srcSet: '', sizes: opts.sizes || DEFAULT_SIZES, width: 0, height: 0 };
        setState(v);
      });

    return () => { cancelled = true; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [cKey]);

  return { src: state.url, srcSet: state.srcSet, sizes: state.sizes, width: state.width, height: state.height };
}
